#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bash ~/.config/polybar/material/scripts/pywal.sh /home/ayami//Wallpaper/wallpaper_001
#bash ~/.config/polybar/shapes/scripts/random.sh
bash ~/.config/polybar/launch.sh --shapes

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           12
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

#----------------boder color----------------------

#-------------------Pink----------------------
#bspc config focused_border_color "#ff79c6"
#bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config presel_feedback_color "#6272a4"

#-------------------gray----------------------
bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

#-------------------blue----------------------
#bspc config normal_border_color "#D358F7"
#bspc config active_border_color "#2E64FE"
#bspc config focused_border_color "#2E64FE"
#bspc config presel_border_color "#2E64FE"


bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle      true
unclutter --ignore-scrooling &

bspc rule -a Google-chrome desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a netease-cloud-music desktop='^4' state=floating
bspc rule -a Joplin desktop='^4'
bspc rule -a Kite desktop='^3' state=floating
bspc rule -a jetbrains-pycharm-ce desktop='^3'
#bspc rule -a jetbrains-clion desktop='^3'
#bspc rule -a jetbrains-datagrip desktop='^3'

#Enable java-based programs to display windows,e.g Pycharm
wmname LG3D
