#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bash ~/.config/polybar/material/scripts/pywal.sh /home/ayami//Wallpaper/wallpaper_001
#bash ~/.config/polybar/shapes/scripts/random.sh
bash ~/.config/polybar/launch.sh --shapes

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

#----------------boder color----------------------

#-------------------purple----------------------
bspc config normal_border_color "#F0F0F0"
bspc config active_border_color "#FF8EFF"
bspc config focused_border_color "#FF8EFF"
bspc config presel_border_color "#FF8EFF"


bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle      true
unclutter --ignore-scrooling &

bspc rule -a Google-chrome desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a netease-cloud-music desktop='^10' state=floating
bspc rule -a Typora desktop='^6'
#bspc rule -a Kite desktop='^3' state=floating
#pycharm community
#bspc rule -a jetbrains-pycharm-ce desktop='^3'
#pycharm Professional
bspc rule -a jetbrains-pycharm desktop='^3'
bspc rule -a jetbrains-clion desktop='^4'
bspc rule -a jetbrains-datagrip desktop='^5'
bspc rule -a jetbrains-studio desktop='^8' state=floating
bspc rule -a jetbrains-toolbox desktop='^9' state=pseudo_tiled

#Enable java-based programs to display windows,e.g Pycharm
wmname LG3D
